Changeset for 20210415
mozmeao/lumbergh pull request #707
Opened 2021-04-15 02:36 UTC by TimAshton

## Description
This PR addresses a group of related issues.

## Issue / Bugzilla link

- GH-609
- GH-700
- GH-702
- GH-704
- GH-705

## Testing
All HTML and CSS tested manually.
Data model change tested manually.

2021-04-19 18:54 UTC, pmac requested changes
I've made just one suggestion. Looking good. I've also asked Craig to have a look for the HTML bits to make sure it's following our guidelines there.

2021-04-19 18:54 UTC, pmac commented on careers/careers/templates/careers/position.jinja
> +        {% if position.is_mofo == False %}
This is the more Python way to write this. Just a style thing mostly, but also allows it to do the right thing if the value happened to be `None` or `""`.
```suggestion
        {% if not position.is_mofo %}
```

2021-04-19 19:05 UTC, craigcook approved these changes
LGTM!

2021-04-20 15:00 UTC, pmac approved these changes

2021-04-20 15:01 UTC, merged